#!/bin/bash
# Clean script for web interface files.
#
# This script removes all files that are generated by build_web.py:
# - docs/bwt_svg/ directory
# - docs/bwt_web.py file
#
# Usage:
#     cd docs
#     ./clean.sh

echo "Cleaning generated web interface files..."

# Remove generated directory
if [ -d "bwt_svg" ]; then
    echo "Removing docs/bwt_svg/"
    rm -rf bwt_svg/
else
    echo "docs/bwt_svg/ not found (already clean)"
fi

# Remove generated consolidated file
if [ -f "bwt_web.py" ]; then
    echo "Removing docs/bwt_web.py"
    rm bwt_web.py
else
    echo "docs/bwt_web.py not found (already clean)"
fi

echo "Clean complete!"
echo "Generated files removed:"
echo "  - docs/bwt_svg/"
echo "  - docs/bwt_web.py"
